version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  backend:
    build:
      context: ./backend
    ports:
      - "8081:8080"
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: three_tier_test_db
      MYSQL_USER: sa
      MYSQL_PASSWORD: root
    ports:
      - "9000:3306"